project:
  type: website
  output-dir: docs

website:
  title: "**RedHD Chile**"
  navbar:
    left:
    - text: asiste
      href: https://forms.gle/jQjDogLKMrajM15YA
    - text: presenta
      href: https://forms.gle/RxnrREyoUjeRifwS6
    - text: equipo
      href: equipo.qmd

  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mainfont: "Hammersmith One"



