project:
  type: website
  output-dir: docs

website:
  title: "**RedHD Chile**"
  navbar:
    left:
    - text: programa
      href: programa.qmd
    - text: c√≥mo participar
      href: participa.qmd
    - text: equipo
      href: equipo.qmd

  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mainfont: "Hammersmith One"



