project:
  type: website
  output-dir: docs

website:
  title: "**RedHD Chile**"
  navbar:
    left:
    - text: inicio
      href: index.qmd
    - text: c√≥mo participar
      href: participa.qmd
    - text: programa
      href: programa.qmd
    - text: ponentes
      href: participantes.qmd
    - text: equipo
      href: equipo.qmd
  page-footer: |
    Sitio web hecho con <i class="fa-solid fa-heart"></i>, <i class="fa-solid fa-mug-hot"></i> y [Quarto](https://quarto.org) por [Riva Quiroga](https://rivaquiroga.cl)
  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mainfont: "Hammersmith One"
